### ISSUE TITLE
Project still working with the redesign?

### ISSUE THREAD

**Issue by MarkusTeufelberger** [mitsuhiko/flatex-pdf-download#1]
I tried to use this to download some pdfs, but didn't manage to get results. Before I dig deeper into it and do a proper writeup/debugging session, can someone please confirm that this is still working at the moment since flatex.at did some rebranding and redesign on their page recently.

**Comment by mitsuhiko** [comment]
It's still working for me. I am typically passing the session id though from the browser, not sure if the login works well right now.

**Comment by mitsuhiko** [comment]
Closing this then :)

**Comment by MarkusTeufelberger** [comment]
I can also confirm it works now. Weird... Thanks for checking!
