### ISSUE TITLE
Not working again

### ISSUE THREAD

**Issue by kaulex99** [mitsuhiko/flatex-pdf-download#11]
Again empty results when trying to download pdf files. Looks like it is related to the new Web-UI.

**Comment by kaulex99** [comment]
I investigated a bit and it looks like the url changed to `"sso_url": "https://www.flatex.at/login.at/sso",` and `"sso_url": "https://www.flatex.de/login.de/sso",`

**Comment by mitsuhiko** [comment]
Updated the URLs but did not verify.
