### ISSUE TITLE
Confusion about correct `sso_url`

### ISSUE THREAD

**Issue by phi-mah** [mitsuhiko/flatex-pdf-download#12]
Thanks for the batch downloader; this is really helpful. 
~~I don't know the history~~ (EDIT: It was #11) that led to 77a88c0, but as of today and when querying the  `de` branch, I had to revert 77a88c0.

| `sso_url` | http response of login function |
| --- | --- |
| https://www.flatex.de/sso | 200 |
| https://www.flatex.de/login.de/sso | 404 |

**Comment by mitsuhiko** [comment]
I do not use flatex.de. Can you send a PR with the correct values?

**Comment by kaulex99** [comment]
@phi-mah  Maybe the issue is related to the difference between Austrian and German servers?

**Comment by phi-mah** [comment]
I don't think so. I checked with:

```
--- a/flatex-fetch.py
+++ b/flatex-fetch.py
@@ -58,7 +58,7 @@ class Fetcher(object):
         return PORTALS[self.portal]["sso_url"]
 
     def login(self, user_id, password):
-        self.session.post(
+        status = self.session.post(
             self.sso_url,
             headers={"User-Agent": USER_AGENT},
             data={
@@ -67,6 +67,7 @@ class Fetcher(object):
                 "tx_flatexaccounts_singlesignonbanking[sessionpass]": "",
             },
         )
+        print(f"login @{self.sso_url}: POST request returned: {status}")
 
     def _request(self, url, data):
         url = urljoin(self.url_base, url)

````

### Results 
##### `python flatex-fetch.py -u <MYUSERNAME> --portal de`
*   `login @https://www.flatex.de/sso: POST request returned: <Response [200]>`  
   queries password, continues with document download
*
  `login @https://www.flatex.de/login.de/sso: POST request returned: <Response [404]>`
  queries password, program exits 

##### `python flatex-fetch.py -u dummy`
_I do not have a `flatex.at` account, but even a dummy username gives some insights:_
* `login @https://www.flatex.at/sso: POST request returned: <Response [200]>`
  queries (dummy) password, program exits 
* `login @https://www.flatex.de/login.de/sso: POST request returned: <Response [404]>`
  queries (dummy) password, program exits 
  
 In any case the updated url values (with the `login`-part) result in an `404` error, whereas with the old values the german version  just works and the at variant returns at least a `200` (Although neither username nor password are correct, but anyhow...).

**Comment by mitsuhiko** [comment]
I just reverted this now. Seems to work at least for me.
