### ISSUE TITLE
PDFs damaged when downloading with script

### ISSUE THREAD

**Issue by kaulex99** [mitsuhiko/flatex-pdf-download#5]
When I download the pdf documents with the script, all of them are damaged and can't be opened. Is there anyone else facing this issue or is it only me?

**Comment by mitsuhiko** [comment]
Please provide more information, in this form this cannot be debugged.

* What operating system are you on?
* Which Python version are you using?
* Do the PDFs work when downloaded from the UI directly?
* What version of the script are you using (commit hash)

**Comment by kaulex99** [comment]
1. MacOS Ventura 13.2 (22D49)
2. Python 3.11.1
3. YES
4. Current main branch (checked out yesterday)

**Comment by mitsuhiko** [comment]
@kaulex99 would you mind mailing me one of the corrupted PDFs?

**Comment by kaulex99** [comment]
@mitsuhiko No, I will send you a general one via email.

**Comment by mitsuhiko** [comment]
I looked at the PDF and it's not a PDF, but a HTML error page ("Blocked"). It's because flatex blocked the script again. Needs investigation.

**Comment by kaulex99** [comment]
Maybe some error handling in the script would be great, just to not download all the pdfs if they are broken. Because the script output looks like if nothing went wrong in general.

**Comment by gaambo** [comment]
FYI: having the same problem. 
I'm using Ubuntu 22 (in WSL 2), Python 3.10.6 using current main branch. I'm using the SESSIONID param if that makes any difference.

**Comment by mitsuhiko** [comment]
Happy to accept PRs. Sadly I don't have much time to deal with this myself.

**Comment by gaambo** [comment]
> maybe #8 solves this issue

i just checked out the PR locally and it worked for me (using session-id and flatex.at). thank you 👍

**Comment by kaulex99** [comment]
@mitsuhiko can you please merge :D

**Comment by mitsuhiko** [comment]
Merged. Thank you.
