### ISSUE TITLE
Include an option to change to flatex.de

### ISSUE THREAD

**Issue by floriangaller** [mitsuhiko/flatex-pdf-download#7]
by changing URL_BASE and SSO_URL to:
URL_BASE = "https://konto.flatex.de/banking-flatex/"
SSO_URL = "https://www.flatex.de/sso"

it is possible to use the tool for the german version of flatex. 
Please include a way of changing these variables during call of the function

**Comment by mitsuhiko** [comment]
Done. You can pass `--portal=de` to the script now.
